src/main/java/com/kh/gw/board/model/dao/AllBoardDao.java
package com.kh.gw.board.model.dao;

import java.util.List;

import org.mybatis.spring.SqlSessionTemplate;

import com.kh.gw.board.model.vo.AllBoard;
import com.kh.gw.board.model.vo.AllBoardReply;
import com.kh.gw.board.model.vo.Attachment;
import com.kh.gw.board.model.vo.PageInfo;
import com.kh.gw.board.model.vo.SearchCriteria;

public interface AllBoardDao {
	/**
     * 게시물 리스트 조회
     * @param boardVO
     * @return
     * @throws Exception
     */
	
	//전사게시판 작성
	public int insertAllBoardForm(SqlSessionTemplate sqlSession,AllBoard allBoard) throws Exception;

	//전사게시판 작성(첨부파일)
	public int insertAllBoardFormFile(SqlSessionTemplate sqlSession, Attachment attachment) throws Exception;
	
	//전사게시판 목록 조회
	public List<AllBoard> selectListAllBoardPaging(PageInfo pi) throws Exception;
	
	//전사게시판 목록 조회 페이징
	public int getListCount() throws Exception;
	
	//전사게시판 조회
	public AllBoard SelectOneAllBoard(String aBoardNo) throws Exception;
	
	//공지사항 조회수
	public void aCount(String aBoardNo) throws Exception;
		
	//전사게시판 수정
	public void updateAllBoardForm(AllBoard allBoard) throws Exception;
	
	//전사게시판 삭제
	public void deleteAllBoard(AllBoard allBoard) throws Exception;

	//게시물 갯수
	public int getAllBoardListCount() throws Exception;
	
	// 댓글 조회
	public List<AllBoardReply> readReply(SqlSessionTemplate sqlSession, AllBoardReply aReply) throws Exception;
	
	// 댓글 작성
	public int insertReply(SqlSessionTemplate sqlSession, AllBoardReply aReply) throws Exception;

	// 댓글 수정
	public int updateReply(SqlSessionTemplate sqlSession, AllBoardReply allBoardReply) throws Exception;
	
	// 댓글 삭제
	public int deleteReply(SqlSessionTemplate sqlSession,String replyNo) throws Exception;

	public Attachment SelectOneFile(String aBoardNo);

	public Attachment selectOneAttachmentBoard(SqlSessionTemplate sqlSession, String attachmentNo);
	
}

src/main/java/com/kh/gw/board/model/dao/AllBoardDaoImpl.java
package com.kh.gw.board.model.dao;

import java.util.List;

import javax.inject.Inject;

import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.session.SqlSession;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.stereotype.Repository;

import com.kh.gw.board.model.vo.AllBoard;
import com.kh.gw.board.model.vo.AllBoardReply;
import com.kh.gw.board.model.vo.Attachment;
import com.kh.gw.board.model.vo.Notice;
import com.kh.gw.board.model.vo.PageInfo;
import com.kh.gw.board.model.vo.SearchCriteria;

@Repository
public class AllBoardDaoImpl implements AllBoardDao{
	
	@Inject
	private SqlSession sqlSession;
	
	//private static String namespace = "AllBoard";

	//전사게시판 작성
	@Override
	public int insertAllBoardForm(SqlSessionTemplate sqlSession,AllBoard allBoard) throws Exception {
		
		return sqlSession.insert("AllBoard.insertAllBoardForm", allBoard);
	}
	
	//전사게시판 첨부파일
	@Override
	public int insertAllBoardFormFile(SqlSessionTemplate sqlSession, Attachment attachment) {

		System.out.println("dao att : " + attachment);
		return sqlSession.insert("AllBoard.insertAttachment", attachment);
	}
	
	//전사게시판 목록 조회
	@Override
	public List<AllBoard> selectListAllBoardPaging(PageInfo pi) throws Exception {

		List<AllBoard> list2 = null;
		
		//몇개의 게시물을 건너뛰고 검색할건지 계산
		int offset = (pi.getCurrentPage() - 1) * pi.getLimit();
				
		RowBounds rowBounds = new RowBounds(offset, pi.getLimit());
		
		return sqlSession.selectList("AllBoard.selectListAllBoardPaging", null, rowBounds);
	}
	
	//전사게시판 목록 조회 카운트
	@Override
	public int getListCount() {
			
		return sqlSession.selectOne("AllBoard.selectListAllBoardCount");
	}

	//전사게시판 조회
	@Override
	public AllBoard SelectOneAllBoard(String aBoardNo) throws Exception {
		
		//System.out.println(aBoardNo);
		return sqlSession.selectOne("AllBoard.selectOneAllBoard", aBoardNo);
	}
	
	//전사게시판 조회(첨부파일)
	@Override
	public Attachment SelectOneFile(String aBoardNo) {
		// TODO Auto-generated method stub
		return sqlSession.selectOne("AllBoard.selectOneAttachment", aBoardNo);
	}
	//다운로드
	@Override
	public Attachment selectOneAttachmentBoard(SqlSessionTemplate sqlSession, String attachmentNo) {
		// TODO Auto-generated method stub
		return sqlSession.selectOne("AllBoard.selectOneAttachmentDown", attachmentNo);
	}
	
	//전사게시판 조회수
	@Override
	public void aCount(String aBoardNo) throws Exception {
		sqlSession.update("AllBoard.aCount", aBoardNo);
	}

	//전사게시판 수정
	@Override
	public void updateAllBoardForm(AllBoard allBoard) throws Exception {
		sqlSession.update("AllBoard.updateAllBoard", allBoard);
	}

	//전사게시판 삭제
	@Override
	public void deleteAllBoard(AllBoard allBoard) throws Exception {
		sqlSession.delete("AllBoard.deleteAllBoard", allBoard);
	}

	//게시물 갯수
	@Override
	public int getAllBoardListCount() throws Exception {
		// TODO Auto-generated method stub
		return sqlSession.selectOne("AllBoard.getAllBoardListCount");
	}
	
	//private static String namespace = "AllBoardReply";
	
	// 댓글 조회
	@Override
	public List<AllBoardReply> readReply(SqlSessionTemplate sqlSession, AllBoardReply aReply) throws Exception {
		return sqlSession.selectList("AllBoardReply.AllBoardReadReply", aReply);
		
	}

	// 댓글 작성
	@Override
	public int insertReply(SqlSessionTemplate sqlSession, AllBoardReply aReply) throws Exception {
		return sqlSession.insert("AllBoardReply.AllBoardInsertReply", aReply);
	}

	//댓글 수정
	@Override
	public int updateReply(SqlSessionTemplate sqlSession, AllBoardReply allBoardReply) throws Exception {
		return sqlSession.update("AllBoardReply.AllBoardUpdateReply", allBoardReply);
	}
	
	//댓글 삭제
	@Override
	public int deleteReply(SqlSessionTemplate sqlSession, String replyNo) throws Exception {
		return sqlSession.delete("AllBoardReply.AllBoardDeleteReply", replyNo);
	}





}

src/main/java/com/kh/gw/board/model/dao/NoticeDao.java
package com.kh.gw.board.model.dao;

import java.util.List;

import org.apache.ibatis.session.SqlSession;
import org.mybatis.spring.SqlSessionTemplate;

import com.kh.gw.board.model.vo.Notice;
import com.kh.gw.board.model.vo.PageInfo;
import com.kh.gw.board.model.vo.Attachment;

public interface NoticeDao {

	/**
     * 게시물 리스트 조회
     * @param boardVO
     * @return
     * @throws Exception
     */

	//메인보드 공지사항 목록 조회
	public List<Notice> selectListNoticeMain() throws Exception;
	
	//공지사항 목록 조회 상단 고정
	public List<Notice> selectListNoticePagingPin( ) throws Exception;
	
	//공지사항 목록 조회
	public List<Notice> selectListNoticePaging(PageInfo pi) throws Exception;

	//공지사항 총 갯수
	public int getListCount() throws Exception;
	
	//공지사항 작성
	public int insertNotice(Notice notice) throws Exception;
	
	//공지사항 조회
	public Notice selectOne(String nBoardNo) throws Exception;

	//공지사항 조회수
	public void nCount(String nBoardNo) throws Exception;
	
	//공지사항 수정
	public void updateNotice(Notice notice) throws Exception;
	
	//공지사항 삭제
	public void deleteNotice(Notice notice) throws Exception;

	//공지사항 작성 첨부파일
	public int insertNoticeAttachment(Attachment attachment) throws Exception;

	//int insertNoticeAttachment(SqlSessionTemplate sqlSession, Attachment at);

	//int deleteNoticeAttachment(SqlSessionTemplate sqlSession, String originPicture);

	
}

src/main/java/com/kh/gw/board/model/dao/NoticeDaoImpl.java
package com.kh.gw.board.model.dao;

import java.util.List;

import javax.inject.Inject;

import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.session.SqlSession;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.stereotype.Repository;

import com.kh.gw.board.model.vo.Notice;
import com.kh.gw.board.model.vo.PageInfo;
import com.kh.gw.board.model.vo.Attachment;

@Repository
public class NoticeDaoImpl implements NoticeDao {

	@Inject
	private SqlSession sqlSession;
	
	private static String namespace = "notice";
	
	//메인보드 공지사항 목록 조회
	public List<Notice> selectListNoticeMain() throws Exception {
		List<Notice> mainList = null;
		
		return sqlSession.selectList(namespace + ".selectListNoticeMain", null);
	}
	
	//공지사항 목록 조회 상단 고정
	public List<Notice> selectListNoticePagingPin() throws Exception {
		List<Notice> listPin = null;
		
		//몇개의 게시물을 건너뛰고 검색할건지 계산
		//int offset = (pi.getCurrentPage() - 1) * pi.getLimit();
				
		//RowBounds rowBounds = new RowBounds(offset, pi.getLimit());
		
		return sqlSession.selectList(namespace + ".selectListNoticePagingPin", null);
	}
	
	
	//공지사항 목록 조회
	public List<Notice> selectListNoticePaging(PageInfo pi) throws Exception {

		List<Notice> list = null;
		
		//몇개의 게시물을 건너뛰고 검색할건지 계산
		int offset = (pi.getCurrentPage() - 1) * pi.getLimit();
				
		RowBounds rowBounds = new RowBounds(offset, pi.getLimit());
		
		return sqlSession.selectList(namespace + ".selectListNoticePaging", null, rowBounds);
		
	}

	//공지사항 총 갯수
	@Override
	public int getListCount() throws Exception {
		return sqlSession.selectOne(namespace + ".selectListNoticeCount");
	}

	//공지사항 작성
	@Override
	public int insertNotice(Notice notice) throws Exception {
		return sqlSession.insert(namespace + ".noticeInsertForm", notice);
	}

	//공지사항 조회
	@Override
	public Notice selectOne(String nBoardNo) throws Exception {
		
		return sqlSession.selectOne(namespace + ".noticeSelectOne", nBoardNo);
	}

	//공지사항 조회수
	@Override
	public void nCount(String nBoardNo) throws Exception {
		sqlSession.update(namespace + ".nCount", nBoardNo);		
	}

	
	//공지사항 수정
	@Override
	public void updateNotice(Notice notice) throws Exception {
		sqlSession.update(namespace + ".noticeUpdate", notice);
	}

	//공지사항 삭제
	@Override
	public void deleteNotice(Notice notice) throws Exception {
		sqlSession.delete(namespace + ".noticeDelete", notice);
	}

	//첨부파일
//	@Override
//	public int insertNoticeAttachment(SqlSessionTemplate sqlSession, Attachment at) {
//
//		return sqlSession.insert(namespace + ".insertNoticeAttachment", at);
//	}
//
//
//	@Override
//	public int deleteNoticeAttachment(SqlSessionTemplate sqlSession, String originPicture) {
//		
//		return sqlSession.delete(namespace + ".deleteNoticeAttachment", originPicture);
//	}

	//공지사항 작성 첨부파일
	@Override
	public int insertNoticeAttachment(Attachment attachment) throws Exception {

//		int result = 0;
//		int length = 0;
//		
//		//for(int i = 0; i < attachment.size(); i++) {
//			int result1 = sqlSession.insert("Attachment.insertNoticeAttachment", attachment.get(i));
//			System.out.println("Dao result1 : " + result1);
//			length += result1;
//		//}
//		
//		if(length == attachment.size()) {
//			result = length;
//			System.out.println("Dao result : " + result);
//			return result;
//		} else {
//			return 0;
//		}
		return sqlSession.insert(namespace + ".insertNoticeAttachment", attachment);
		
	}



}

src/main/java/com/kh/gw/board/model/dao/SurveyDao.java
package com.kh.gw.board.model.dao;

import java.util.List;

import org.mybatis.spring.SqlSessionTemplate;

import com.kh.gw.board.model.vo.PageInfo;
import com.kh.gw.board.model.vo.Survey;
import com.kh.gw.board.model.vo.SurveyAnswer;
import com.kh.gw.board.model.vo.SurveyQuestion;

public interface SurveyDao {
	
		//설문 작성
		public int insertSurvey(SqlSessionTemplate sqlSession, Survey survey) throws Exception;
		
		//메인보드 설문 목록 조회
		public List<Survey> selectListSurveyMain(SqlSessionTemplate sqlSession) throws Exception;
		
		//설문 목록 조회
		public List<Survey> selectListSurveyPaging(SqlSessionTemplate sqlSession, PageInfo pi) throws Exception;
		
		//설문 목록 조회 페이징
		public int getListCount(SqlSessionTemplate sqlSession) throws Exception;
		
		//설문 조회
		public Survey SelectOneSurvey(SqlSessionTemplate sqlSession, Survey survey) throws Exception;
		
		//설문 조회수
		void sCount(SqlSessionTemplate sqlSession, Survey survey) throws Exception;

//------------------------------------------------------------------------------------------------------

		//설문 질문 작성
		public int insertSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sq);
		//public int insertSurveyQuestion(SqlSessionTemplate sqlSession, List<SurveyQuestion> list4) throws Exception;

		//설문 선택 작성
		public int insertSurveyAnswer(SqlSessionTemplate sqlSession, SurveyAnswer sa);
		
		//설문 질문 조회
		public List<SurveyQuestion> SelectOneSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sq);
		
		//설문 결과 조회
		public List<SurveyAnswer> SelectOneSurveyAnswer(SqlSessionTemplate sqlSession, SurveyAnswer sa) throws Exception;

		//설문 마감처리
		public void deadLine(SqlSessionTemplate sqlSession, Survey survey) throws Exception;
}

src/main/java/com/kh/gw/board/model/dao/SurveyDaoImpl.java
package com.kh.gw.board.model.dao;

import java.util.List;

import org.apache.ibatis.session.RowBounds;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.stereotype.Repository;

import com.kh.gw.board.model.vo.Notice;
import com.kh.gw.board.model.vo.PageInfo;
import com.kh.gw.board.model.vo.Survey;
import com.kh.gw.board.model.vo.SurveyAnswer;
import com.kh.gw.board.model.vo.SurveyQuestion;

@Repository
public class SurveyDaoImpl implements SurveyDao{

	private static String namespace = "survey";
	
		//설문 작성
		@Override
		public int insertSurvey(SqlSessionTemplate sqlSession, Survey survey) throws Exception {
			
			return sqlSession.insert(namespace + ".insertSurvey", survey);
		}
		
		//설문 질문 작성
		@Override
		public int insertSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sq) {

			return sqlSession.insert(namespace + ".insertSurveyQuestion", sq);
		}
		
		//설문 선택 작성
		@Override
		public int insertSurveyAnswer(SqlSessionTemplate sqlSession, SurveyAnswer sa) {

			return sqlSession.insert(namespace + ".insertSurveyAnswer", sa);
		}
	
		//메인보드 설문 목록 작성
		@Override
		public List<Survey> selectListSurveyMain(SqlSessionTemplate sqlSession) throws Exception {
			List<Survey> mainSurveyList = null;
			
			return sqlSession.selectList(namespace + ".selectListSurveyMain", null);
		}

		//설문 목록 조회
		@Override
		public List<Survey> selectListSurveyPaging(SqlSessionTemplate sqlSession, PageInfo pi) throws Exception {

			List<Survey> list3 = null;
			
			//몇개의 게시물을 건너뛰고 검색할건지 계산
			int offset = (pi.getCurrentPage() - 1) * pi.getLimit();
					
			RowBounds rowBounds = new RowBounds(offset, pi.getLimit());
			
			return sqlSession.selectList(namespace + ".selectListSurveyPaging", null, rowBounds);
		}
		
		//설문 목록 조회 카운트
		@Override
		public int getListCount(SqlSessionTemplate sqlSession) throws Exception {
			
			return sqlSession.selectOne(namespace + ".selectListSurveyCount");
			
			
		}
		
		//설문 조회
		@Override
		public Survey SelectOneSurvey(SqlSessionTemplate sqlSession, Survey survey) throws Exception {
			
			return sqlSession.selectOne(namespace + ".selectOneSurvey", survey);
		}
		
		//설문 질문 조회
		@Override
		public List<SurveyQuestion> SelectOneSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sq) {
			
			return sqlSession.selectList(namespace + ".selectOneSurveyQuestion", sq);
		}
		
		//설문 결과 조회
		@Override
		public List<SurveyAnswer> SelectOneSurveyAnswer(SqlSessionTemplate sqlSession, SurveyAnswer sa) {
					
			return sqlSession.selectList(namespace + ".selectOneSurveyAnswer", sa);
		}
		
		//설문 조회수
		@Override
		public void sCount(SqlSessionTemplate sqlSession, Survey survey) throws Exception {
			sqlSession.update(namespace + ".sCount", survey);
		}

		//설문 마감처리
		@Override
		public void deadLine(SqlSessionTemplate sqlSession, Survey survey) throws Exception {
			sqlSession.update(namespace + ".deadLine", survey);
		}
		
}

src/main/java/com/kh/gw/board/model/dao/SurveyQuestionDao.java
package com.kh.gw.board.model.dao;

import java.util.List;

import org.mybatis.spring.SqlSessionTemplate;

import com.kh.gw.board.model.vo.SurveyQuestion;

public interface SurveyQuestionDao {

//	//설문 질문 작성
//	public int insertSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sQuestionContent);
//	//public int insertSurveyQuestion(SqlSessionTemplate sqlSession, List<SurveyQuestion> list4) throws Exception;
//
//	//설문 질문 조회
//	public List<SurveyQuestion> SelectOneSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sq);
}

src/main/java/com/kh/gw/board/model/dao/SurveyQuestionDapImpl.java
package com.kh.gw.board.model.dao;

import java.util.List;

import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.stereotype.Repository;

import com.kh.gw.board.model.vo.SurveyQuestion;

@Repository
public class SurveyQuestionDapImpl implements SurveyQuestionDao{

	private static String namespace = "Survey";

	
	/*
	 * @Override public int insertSurveyQuestion(SqlSessionTemplate sqlSession,
	 * List<SurveyQuestion> list4) throws Exception { return
	 * sqlSession.insert(namespace + ".insertSurveyQuestion", list4); }
	 */
	
	
	
	
//	@Override
//	public int insertSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sQuestionContent) {
//		// TODO Auto-generated method stub
//		return sqlSession.insert(namespace + ".insertSurveyQuestion", sQuestionContent);
//	}
//
//
//	@Override
//	public List<SurveyQuestion> SelectOneSurveyQuestion(SqlSessionTemplate sqlSession, SurveyQuestion sq) {
//		
//		return sqlSession.selectList(namespace + ".selectOneSurveyQuestion", sq);
//	}

}

src/main/java/com/kh/gw/board/model/exception/AllBoardException.java
package com.kh.gw.board.model.exception;

public class AllBoardException extends Exception{
	public AllBoardException(String msg) {
		super(msg);
	}
}

src/main/webapp/WEB-INF/views/board/allBoard/allBoardList.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<title>Insert title here</title>
<style>	
	.contentTitle {
	}
	
	.contentDiv {
	height:680px;
	}
	
	table {
	border-collapse: separate;
	width:90%;
	margin:auto;
	text-align:center;
	}
	
	.boardTable td {
	boarder:1px solid lightgray;
	text-align:center;
	border-bottom: 2px solid lightgray;
	padding-bottom: 5px;
	padding-top: 5px;
	text-align: center;
	height: 30px;
	}
	
	.keyword {
	vertical-align:top;
  	background-image : url('search.png'); 
 	background-position:top right; 
 	background-repeat:no-repeat;

	}

	#button2{
	width: 50px;
	height: 30px;
	border: 0px;
	background: lightgray;
	outline: none;
	float: right;
	color: white;
	}
	
	#insertBtn {
	width:80px;
	background-color: #0871B9;
	border: 1px solid #0871B9;
	color: white;
	padding: 7px 20px;
	text-align: center;
	text-decoration: none;
	display: inline-block;
	border-radius: 5px;
	font-size: 12px;
	}
	
	#pagingDiv {
	height:60px;
	}
	
</style>
<script>
</script>
</head>
<body>
	<div class="wrap">
	<!-- 메뉴바 include -->

	<jsp:include page="../boardMenubar.jsp" />
	<!-- board 메뉴바 include -->

		<!-- 본문 영역 시작 -->
		<!-- 여기 본문에서 뷰페이지 만드시면 됩니다!!  -->

		<div class="content">
			<b class="contentTitle">전사 게시판</b>
			<br><br>
			<div class="contentDiv" style="width:800px">
			<br><br>
				<%-- <div class="contentDiv2">
					<select style="border:2px solid lightgray; width:80px; height:30px; text-align-last:center;">
						<option>제목</option>
						<option>번호</option>
					</select>
					<input type="text" class="keyword" style="border:2px solid lightgray; width:200px; height:30px;">
					<button><img src="${ contextPath }/resources/images/icons/search.png" width="20px"></button>
				</div> --%>
					<table class="boardTable">
						<colgroup>
							<col width="10%" />
							<col width="10%"/>
							<col width="40%" />
							<col width="15%" />
							<col width="15%" />
							<col width="10%" />
						</colgroup>
						<!-- <tr>
								<td colspan="5">
								<div id="search2">
									<input id="input2" type="text" placeholder="검색어 입력">
									<button id="button2">검색</button>
								</td>
								</div>
						</tr> -->
						<tr>
							<td colspan="6" style="text-align:right;">
								<select style="border:2px solid lightgray; width:80px; height:30px; text-align-last:center;">
									<option>제목</option>
									<option>번호</option>
								</select>
									<input type="text" class="keyword" style="border:2px solid lightgray; width:200px; height:30px;">
									<%-- <button><img src="${ contextPath }/resources/images/icons/search.png" width="20px"></button> --%>
									<button id="button2">검색</button>
							</td>
						</tr>
						<tr style="background:#0871B9; color:white; vertical-align:middle;">
							<td><label>번호</label></td>
							<td><label>분류</label></td>
							<td><label>제목</label></td>
							<td><label>작성자</label></td>
							<td><label>작성일</label></td>
							<td><label>조회수</label></td>
						</tr>
						
						<c:forEach items="${list2}" var="list2" varStatus="status">
						
						<tr>
							<td>${(pi.listCount-status.index)-((pi.currentPage-1)*10)}</td>
							<td>공통</td>
							<td><a  href="selectOneAllBoard.bo?aBoardNo=${list2.aBoardNo}">${list2.aTitle}</a></td>
							<td>${list2.empName}</td>
							<td><fmt:formatDate value="${list2.aEnrollDate }" pattern="yy/MM/dd"/>&nbsp;</td>
							<td>${list2.aCount}</td>
						</tr>
						
						</c:forEach>
						
				</table>
				
					<!-- 페이징 -->
					<div id="pagingDiv" align="center" >					
							
						<ul class="pagination">
						<!-- li태그의 클래스에 disabled를 넣으면 마우스를 위에 올렸을 때 클릭 금지 마크가 나오고 클릭도 되지 않는다.-->
						<!-- disabled의 의미는 앞의 페이지가 존재하지 않다는 뜻이다. -->
							<c:if test="${ pi.currentPage <= 1 }">
								<li class="disabled">
									<a href="${ blistBack }">
										<span>«</span>
									</a>
								</li>
							</c:if>
							<c:if test="${ pi.currentPage > 1 }">
								<c:url var="blistBack" value="selectListAllBoard.bo">
									<c:param name="currentPage" value="${ pi.currentPage - 1 }" />
								</c:url>
								<li>
									<a href="${ blistBack }">
										<span>«</span>
									</a>
								</li>
							</c:if>
							 
							<c:forEach var="p" begin="${ pi.startPage }" end="${ pi.endPage }">
								<c:if test="${ p eq pi.currentPage }">
									<li class="active"><a href="#">${ p }</a></li>
								</c:if>
								<c:if test="${ p ne pi.currentPage }">
									<c:url var="blistCheck" value="selectListAllBoard.bo">
										<c:param name="currentPage" value="${ p }" />
									</c:url>
									<li><a href="${ blistCheck }">${ p }</a></li>
								</c:if>				
							</c:forEach>
							
							
							<c:if test="${ pi.currentPage >= pi.endPage }">
								<li class="disabled">
									<a href="${ blistBack }">
										<span>»</span>
									</a>
								</li>
							</c:if>
							
							<c:if test="${ pi.currentPage < pi.endPage }">
								<c:url var="blistEnd" value="selectListAllBoard.bo">
									<c:param name="currentPage" value="${ pi.currentPage + 1 }" />
								</c:url>
								<li>
									<a href="${ blistEnd }">
										<span>»</span>
									</a>
								</li>								 
							</c:if>	
							
						</ul>
		
					</div>
					
					
<!-- 					검색 창 -->

					  <%-- <div class="search">
					    <select name="searchType">
					      <option value="n"<c:out value="${scri.searchType == null ? 'selected' : ''}"/>>-----</option>
					      <option value="t"<c:out value="${scri.searchType eq 't' ? 'selected' : ''}"/>>제목</option>
					      <option value="c"<c:out value="${scri.searchType eq 'c' ? 'selected' : ''}"/>>내용</option>
					      <option value="w"<c:out value="${scri.searchType eq 'w' ? 'selected' : ''}"/>>작성자</option>
					      <option value="tc"<c:out value="${scri.searchType eq 'tc' ? 'selected' : ''}"/>>제목+내용</option>
					    </select>
					
					    <input type="text" name="keyword" id="keywordInput" value="${scri.keyword}"/>
					
					    <button id="searchBtn" type="button">검색</button>
					    
					  </div> --%>
	<!-- 					검색 창 -->				
							

				<div style="text-align:right;">
					<label style="margin-right:43px; text-align:right;">
						<br><br>
						<button type="submit" class="formBtn" id="insertBtn" onclick="location.href='insertAllBoardForm.bo'">작성</button>
					</label>
				</div>
				
				
				
				
				
				
				
				
				
			</div>
			<br><br><br><br>
			
			<!-- <b class="contentTitle">기안 진행 문서</b>
			<br><br>
			<div class="contentDiv">두번째 Div</div>
			<br><br><br><br>
			
			<b class="contentTitle">완료 문서</b>
			<br><br>
			<div class="contentDiv">세번째 Div</div> -->
		</div>
		<!-- 본문 영역 끝 -->










		<!-- footer 영역 시작 -->
		<footer class="footer"></footer>
		<!-- footer 영역 끝-->


	</div>
	
</body>
</html>